import { gql } from '@apollo/client';
import { HomePage } from 'containers/home';
import Head from 'next/head';
import client from 'services/apollo';
import { useQuery } from '@apollo/client';

const MY_QUERY = gql`
  query {
    users {
      data {
        id
        attributes {
          title
        }
      }
    }
  }
`;

export default function Home() {
  const { data } = useQuery(MY_QUERY);

  console.log(data);

  return (
    <>
      <Head>
        <title>Precificação rápida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage />
    </>
  );
}
