import { HomePage } from 'containers/home';
import Head from 'next/head';
import { themeState } from 'store';

export default function Home() {
  const theme = themeState(state => state.dark);

  return (
    <>
      <Head>
        <title>Precificação rápida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage />
    </>
  );
}
